name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Run tests
        run: iverilog -g2012 -o compiled src/mvm_uart_system.v src/uart_rx.v src/uart_tx.v src/axis_matvec_mul.v src/matvec_mul.v src/skid_buffer.v test/mvm_uart_system_tb.sv test/simple_axis_tb.sv src/project.v && ./compiled
